export const HOME_PAGE_ROUTE = '/home*'
export const LOGIN_PAGE_ROUTE = '/login'
export const PROFILE_PAGE_ROUTE = '/profile'
export const PROJECT_PAGE_ROUTE = '/projects'
export const PROJECT_MVP_PAGE_ROUTE = '/projectmvp'