export const GET_CLIENT_PAGE_BY_ID_SUCCESS = 'GET_CLIENT_PAGE_BY_ID_SUCCESS'
export const GET_CLIENT_PAGE_BY_ID_FAILED = 'GET_CLIENT_PAGE_BY_ID_FAILED'

export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_FAILED = 'GET_CLIENTS_FAILED'

export const CLEAR_CLIENT_PAGE_STATE = 'CLEAR_CLIENT_PAGE_STATE'
export const CLEAR_CLIENTS_STATE = 'CLEAR_CLIENTS_STATE'

export const ADD_NEW_PARENT_EMAIL_ONCHANGE = 'ADD_NEW_PARENT_EMAIL_ONCHANGE'
export const ADD_NEW_PARENT_PASSWORD_ONCHANGE = 'ADD_NEW_PARENT_PASSWORD_ONHCANGE'
export const ADD_NEW_PARENT_NICKNAME_ONCHANGE = 'ADD_NEW_PARENT_NICKNAME_ONHCANGE'
export const ADD_NEW_PARENT_FIRSTNAME_ONCHANGE = 'ADD_NEW_PARENT_FIRSTNAME_ONCHANGE'
export const ADD_NEW_PARENT_LASTNAME_ONCHANGE = 'ADD_NEW_PARENT_LASTNAME_ONCHANGE'
export const ADD_NEW_PARENT_MIDDLENAME_ONCHANGE = 'ADD_NEW_PARENT_MIDDLENAME_ONCHANGE'
