export const GET_CLIENT_PAGE_BY_ID_SUCCESS = 'GET_CLIENT_PAGE_BY_ID_SUCCESS'
export const GET_CLIENT_PAGE_BY_ID_FAILED = 'GET_CLIENT_PAGE_BY_ID_FAILED'

export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_FAILED = 'GET_CLIENTS_FAILED'

export const CLEAR_CLIENT_PAGE_STATE = 'CLEAR_CLIENT_PAGE_STATE'
export const CLEAR_CLIENTS_STATE = 'CLEAR_CLIENTS_STATE'