export const GET_COURSE_PAGE_BY_ID_SUCCESS = 'GET_COURSE_PAGE_BY_ID_SUCCESS'
export const GET_COURSE_PAGE_BY_ID_FAILED = 'GET_COURSE_PAGE_BY_ID_FAILED'

export const GET_ALL_COURSE_PAGES_SUCCESS = 'GET_ALL_COURSE_PAGES_SUCCESS'
export const GET_ALL_COURSE_PAGES_FAILED = 'GET_ALL_COURSE_PAGES_FAILED'