export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS'
export const GET_PROFILE_BY_ID_FAILED = 'GET_PROFILE_BY_ID_FAILED'

export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE'

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED'

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'