export const GET_PROJECT_PAGE_BY_ID_SUCCESS = 'GET_PROJECT_PAGE_BY_ID_SUCCESS'
export const GET_PROJECT_PAGE_BY_ID_FAILED = 'GET_PROJECT_PAGE_BY_ID_FAILED'

export const CREATE_PROJECT_PAGE_SUCCESS = 'CREATE_PROJECT_PAGE_SUCCESS'
export const CREATE_PROJECT_PAGE_FAILED = 'CREATE_PROJECT_PAGE_FAILED'

export const DELETE_PROJECT_PAGE_SUCCESS = 'DELETE_PROJECT_PAGE_SUCCESS'
export const DELETE_PROJECT_PAGE_FAILED = 'DELETE_PROJECT_PAGE_FAILED'

export const UPDATE_PROJECT_PAGE_SUCCESS = 'UPDATE_PROJECT_PAGE_SUCCESS'
export const UPDATE_PROJECT_PAGE_FAILED = 'UPDATE_PROJECT_PAGE_FAILED'

export const CLEAR_PROJECT_PAGE_STATE = 'CLEAR_PROJECT_PAGE_STATE'
export const CLEAR_MY_PROJECTS_STATE = 'CLEAR_MY_PROJECTS_STATE'

export const GET_PROJECT_PAGE_BY_ACCESS_TOKEN_SUCCESS = 'GET_PROJECT_PAGE_BY_ACCESS_TOKEN_SUCCESS'
export const GET_PROJECT_PAGE_BY_ACCESS_TOKEN_FAILED = 'GET_PROJECT_PAGE_BY_ACCESS_TOKEN_FAILED'