export const GET_PROJECT_PAGE_BY_ID_SUCCESS = 'GET_PROJECT_PAGE_BY_ID_SUCCESS'
export const GET_PROJECT_PAGE_BY_ID_FAILED = 'GET_PROJECT_PAGE_BY_ID_FAILED'

export const GET_ALL_PROJECT_PAGES_SUCCESS = 'GET_ALL_PROJECT_PAGES_SUCCESS'
export const GET_ALL_PROJECT_PAGES_FAILED = 'GET_ALL_PROJECT_PAGES_FAILED'

export const CREATE_PROJECT_PAGE_SUCCESS = 'CREATE_PROJECT_PAGE_SUCCESS'
export const CREATE_PROJECT_PAGE_FAILED = 'CREATE_PROJECT_PAGE_FAILED'

export const DELETE_PROJECT_PAGE_SUCCESS = 'DELETE_PROJECT_PAGE_SUCCESS'
export const DELETE_PROJECT_PAGE_FAILED = 'DELETE_PROJECT_PAGE_FAILED'

export const UPDATE_PROJECT_PAGE_SUCCESS = 'UPDATE_PROJECT_PAGE_SUCCESS'
export const UPDATE_PROJECT_PAGE_FAILED = 'UPDATE_PROJECT_PAGE_FAILED'

export const ONCHANGE_PROJECT_PAGE_TITLE = 'ONCHANGE_PROJECT_PAGE_TITLE'
export const ONCHANGE_PROJECT_PAGE_INSTRUCTION = 'ONCHANGE_PROJECT_PAGE_INSTRUCTION'
export const ONCHANGE_PROJECT_PAGE_NOTES = 'ONCHANGE_PROJECT_PAGE_NOTES'

export const ONSHARED_PROJECT = 'ONSHARED_PROJECT'