export const GET_ALL_ROBBO_GROUPS_SUCCESS = 'GET_ALL_ROBBO_GROUPS_SUCCESS'
export const GET_ALL_ROBBO_GROUPS_FAILED = 'GET_ALL_ROBBO_GROUPS_FAILED'

export const UPDATE_ROBBO_GROUP_SUCCESS = 'UPDATE_ROBBO_GROUP_SUCCESS'
export const UPDATE_ROBBO_GROUP_FAILED = 'UPDATE_ROBBO_GROUP_FAILED'