export const GET_ALL_ROBBO_UNITS_SUCCESS = 'GET_ALL_ROBBO_UNITS_SUCCESS'
export const GET_ALL_ROBBO_UNITS_FAILED = 'GET_ALL_ROBBO_UNITS_FAILED'

export const CREATE_ROBBO_UNIT_SUCCESS = 'CREATE_ROBBO_UNIT_SUCCESS'
export const CREATE_ROBBO_UNIT_FAILED = 'CREATE_ROBBO_UNIT_FAILED'

export const DELETE_ROBBO_UNIT_SUCCESS = 'DELETE_ROBBO_UNIT_SUCCESS'
export const DELETE_ROBBO_UNIT_FAILED = 'DELETE_ROBBO_UNIT_FAILED'

export const UPDATE_ROBBO_UNIT_SUCCESS = 'UPDATE_ROBBO_UNIT_SUCCESS'
export const UPDATE_ROBBO_UNIT_FAILED = 'UPDATE_ROBBO_UNIT_FAILED'

export const GET_ROBBO_UNIT_BY_ID_SUCCESS = 'GET_ROBBO_UNIT_BY_ID_SUCCESS'
export const GET_ROBBO_UNIT_BY_ID_FAILED = 'GET_ROBBO_UNIT_BY_ID_FAILED'

export const CREATE_ROBBO_GROUP_SUCCESS = 'CREATE_ROBBO_GROUP_SUCCESS'
export const CREATE_ROBBO_GROUP_FAILED = 'CREATE_ROBBO_GROUP_FAILED'

export const DELETE_ROBBO_GROUP_SUCCESS = 'DELETE_ROBBO_GROUP_SUCCESS'
export const DELETE_ROBBO_GROUP_FAILED = 'DELETE_ROBBO_GROUP_FAILED'

export const ADD_STUDENT_TO_ROBBO_GROUP_SUCCESS = 'ADD_STUDENT_TO_ROBBO_GROUP_SUCCESS'
export const ADD_STUDENT_TO_ROBBO_GROUP_FAILED = 'ADD_STUDENT_TO_ROBBO_GROUP_FAILED'

export const DELETE_STUDENT_FROM_ROBBO_GROUP_SUCCESS = 'DELETE_STUDENT_FROM_ROBBO_GROUP_SUCCESS'
export const DELETE_STUDENT_FROM_ROBBO_GROUP_FAILED = 'DELETE_STUDENT_FROM_ROBBO_GROUP_FAILED'

export const GET_ROBBO_GROUP_BY_ID_SUCCESS = 'GET_ROBBO_GROUP_BY_ID_SUCCESS'
export const GET_ROBBO_GROUP_BY_ID_FAILED = 'GET_ROBBO_GROUP_BY_ID_FAILED'

export const GET_ROBBO_GROUPS_BY_ROBBO_UNIT_ID_SUCCESS = 'GET_ROBBO_GROUPS_BY_ROBBO_UNIT_ID_SUCCESS'
export const GET_ROBBO_GROUPS_BY_ROBBO_UNIT_ID_FAILED = 'GET_ROBBO_GROUPS_BY_ROBBO_UNIT_ID_FAILED'
