export const GET_ALL_ROBBO_UNITS_SUCCESS = 'GET_ALL_ROBBO_UNITS_SUCCESS'
export const GET_ALL_ROBBO_UNITS_FAILED = 'GET_ALL_ROBBO_UNITS_FAILED'

export const CREATE_ROBBO_UNIT_SUCCESS = 'CREATE_ROBBO_UNIT_SUCCESS'
export const CREATE_ROBBO_UNIT_FAILED = 'CREATE_ROBBO_UNIT_FAILED'

export const DELETE_ROBBO_UNIT_SUCCESS = 'DELETE_ROBBO_UNIT_SUCCESS'
export const DELETE_ROBBO_UNIT_FAILED = 'DELETE_ROBBO_UNIT_FAILED'

export const UPDATE_ROBBO_UNIT_SUCCESS = 'UPDATE_ROBBO_UNIT_SUCCESS'
export const UPDATE_ROBBO_UNIT_FAILED = 'UPDATE_ROBBO_UNIT_FAILED'

export const GET_ROBBO_UNIT_BY_ID_SUCCESS = 'GET_ROBBO_UNIT_BY_ID_SUCCESS'
export const GET_ROBBO_UNIT_BY_ID_FAILED = 'GET_ROBBO_UNIT_BY_ID_FAILED'