export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS'
export const GET_TEACHERS_FAILED = 'GET_TEACHERS_FAILED'

export const CLEAR_TEACHERS_STATE = 'CLEAR_TEACHERS_STATE'

export const ADD_TEACHER_SUCCESS = 'ADD_TEACHER_SUCCESS'
export const ADD_TEACHER_FAILED = 'ADD_TEACHER_FAILED'