export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS'
export const GET_TEACHERS_FAILED = 'GET_TEACHERS_FAILED'

export const CLEAR_TEACHERS_STATE = 'CLEAR_TEACHERS_STATE'

export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS'
export const CREATE_TEACHER_FAILED = 'CREATE_TEACHER_FAILED'

export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS'
export const DELETE_TEACHER_FAILED = 'DELETE_TEACHER_FAILED'

export const GET_ROBBO_GROUPS_BY_TEACHER_ID_SUCCESS = 'GET_ROBBO_GROUPS_BY_TEACHER_ID_SUCCESS'
export const GET_ROBBO_GROUPS_BY_TEACHER_ID_FAILED = 'GET_ROBBO_GROUPS_BY_TEACHER_ID_FAILED'