export const GET_UNIT_ADMINS_SUCCESS = 'GET_UNIT_ADMINS_SUCCESS'
export const GET_UNIT_ADMINS_FAILED = 'GET_UNIT_ADMINS_FAILED'

export const CREATE_UNIT_ADMIN_SUCCESS = 'CREATE_UNIT_ADMIN_SUCCESS'
export const CREATE_UNIT_ADMIN_FAILED = 'CREATE_UNIT_ADMIN_FAILED'

export const DELETE_UNIT_ADMIN_SUCCESS = 'DELETE_UNIT_ADMIN_SUCCESS'
export const DELETE_UNIT_ADMIN_FAILED = 'DELETE_UNIT_ADMIN_FAILED'