export const GET_CLIENT_PAGE_BY_ID = 'GET_CLIENT_PAGE_BY_ID'
export const GET_CLIENTS = 'GET_CLIENTS'
export const ADD_PARENT_REQUEST = 'ADD_PARENT_REQUEST'
export const CREATE_CHILDREN_REQUEST = 'CREATE_CHILDREN_REQUEST'