export const GET_TEACHERS = 'GET_TEACHERS'
export const CREATE_TEACHER = 'CREATE_TEACHER'
export const DELETE_TEACHER = 'DELETE_TEACHER'
export const GET_ROBBO_GROUPS_BY_TEACHER_ID = 'GET_ROBBO_GROUPS_BY_TEACHER_ID'